//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SensorSet.Model.SensorSet
{

    [Persistent(@"auth.Users")]
    public partial class auth_Users : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fLogin;
        [Size(SizeAttribute.Unlimited)]
        public string Login
        {
            get { return fLogin; }
            set { SetPropertyValue<string>("Login", ref fLogin, value); }
        }
        string fPassword;
        [Size(SizeAttribute.Unlimited)]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>("Password", ref fPassword, value); }
        }
        string fFirstName;
        [Size(20)]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>("FirstName", ref fFirstName, value); }
        }
        string fMiddleName;
        [Size(20)]
        public string MiddleName
        {
            get { return fMiddleName; }
            set { SetPropertyValue<string>("MiddleName", ref fMiddleName, value); }
        }
        string fLastName;
        [Size(20)]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>("LastName", ref fLastName, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
        DateTime fDeletedDate;
        public DateTime DeletedDate
        {
            get { return fDeletedDate; }
            set { SetPropertyValue<DateTime>("DeletedDate", ref fDeletedDate, value); }
        }
        [Association(@"device_EquipmentReferencesauth_Users")]
        public XPCollection<device_Equipment> device_Equipments { get { return GetCollection<device_Equipment>("device_Equipments"); } }
        [Association(@"device_EquipmentTypeReferencesauth_Users")]
        public XPCollection<device_EquipmentType> device_EquipmentTypes { get { return GetCollection<device_EquipmentType>("device_EquipmentTypes"); } }
    }

}
