//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SensorSet.Model.SensorSet
{

    [Persistent(@"device.Equipment")]
    public partial class device_Equipment : XPLiteObject
    {
        Guid fGUID;
        [Key(true)]
        public Guid GUID
        {
            get { return fGUID; }
            set { SetPropertyValue<Guid>("GUID", ref fGUID, value); }
        }
        device_EquipmentType fEquipmentTypeGUID;
        [Association(@"device_EquipmentReferencesdevice_EquipmentType")]
        public device_EquipmentType EquipmentTypeGUID
        {
            get { return fEquipmentTypeGUID; }
            set { SetPropertyValue<device_EquipmentType>("EquipmentTypeGUID", ref fEquipmentTypeGUID, value); }
        }
        device_EquipmentCategory fEquipmentCategoryGUID;
        [Association(@"device_EquipmentReferencesdevice_EquipmentCategory")]
        public device_EquipmentCategory EquipmentCategoryGUID
        {
            get { return fEquipmentCategoryGUID; }
            set { SetPropertyValue<device_EquipmentCategory>("EquipmentCategoryGUID", ref fEquipmentCategoryGUID, value); }
        }
        device_Equipment fParentGUID;
        [Association(@"device_EquipmentReferencesdevice_Equipment")]
        public device_Equipment ParentGUID
        {
            get { return fParentGUID; }
            set { SetPropertyValue<device_Equipment>("ParentGUID", ref fParentGUID, value); }
        }
        string fInventoryNumber;
        [Size(50)]
        public string InventoryNumber
        {
            get { return fInventoryNumber; }
            set { SetPropertyValue<string>("InventoryNumber", ref fInventoryNumber, value); }
        }
        string fSerialNumber;
        [Size(64)]
        public string SerialNumber
        {
            get { return fSerialNumber; }
            set { SetPropertyValue<string>("SerialNumber", ref fSerialNumber, value); }
        }
        DateTime fManufacturingDate;
        public DateTime ManufacturingDate
        {
            get { return fManufacturingDate; }
            set { SetPropertyValue<DateTime>("ManufacturingDate", ref fManufacturingDate, value); }
        }
        DateTime fStartUseDate;
        public DateTime StartUseDate
        {
            get { return fStartUseDate; }
            set { SetPropertyValue<DateTime>("StartUseDate", ref fStartUseDate, value); }
        }
        string fIpAddress;
        [Size(15)]
        public string IpAddress
        {
            get { return fIpAddress; }
            set { SetPropertyValue<string>("IpAddress", ref fIpAddress, value); }
        }
        string fPort;
        [Size(10)]
        public string Port
        {
            get { return fPort; }
            set { SetPropertyValue<string>("Port", ref fPort, value); }
        }
        decimal fBalanceCost;
        public decimal BalanceCost
        {
            get { return fBalanceCost; }
            set { SetPropertyValue<decimal>("BalanceCost", ref fBalanceCost, value); }
        }
        auth_Users fChangedUserID;
        [Association(@"device_EquipmentReferencesauth_Users")]
        public auth_Users ChangedUserID
        {
            get { return fChangedUserID; }
            set { SetPropertyValue<auth_Users>("ChangedUserID", ref fChangedUserID, value); }
        }
        int fUseMonths;
        public int UseMonths
        {
            get { return fUseMonths; }
            set { SetPropertyValue<int>("UseMonths", ref fUseMonths, value); }
        }
        decimal fRemainingBalance;
        public decimal RemainingBalance
        {
            get { return fRemainingBalance; }
            set { SetPropertyValue<decimal>("RemainingBalance", ref fRemainingBalance, value); }
        }
        DateTime fGarantyPeriod;
        public DateTime GarantyPeriod
        {
            get { return fGarantyPeriod; }
            set { SetPropertyValue<DateTime>("GarantyPeriod", ref fGarantyPeriod, value); }
        }
        DateTime fDeletedDate;
        public DateTime DeletedDate
        {
            get { return fDeletedDate; }
            set { SetPropertyValue<DateTime>("DeletedDate", ref fDeletedDate, value); }
        }
        DateTime fDateCreate;
        public DateTime DateCreate
        {
            get { return fDateCreate; }
            set { SetPropertyValue<DateTime>("DateCreate", ref fDateCreate, value); }
        }
        DateTime fDateModify;
        public DateTime DateModify
        {
            get { return fDateModify; }
            set { SetPropertyValue<DateTime>("DateModify", ref fDateModify, value); }
        }
        DateTime fDateOfChange;
        public DateTime DateOfChange
        {
            get { return fDateOfChange; }
            set { SetPropertyValue<DateTime>("DateOfChange", ref fDateOfChange, value); }
        }
        [Association(@"device_EquipmentReferencesdevice_Equipment")]
        public XPCollection<device_Equipment> device_EquipmentCollection { get { return GetCollection<device_Equipment>("device_EquipmentCollection"); } }
        [Association(@"device_EquipmentCharacterParamReferencesdevice_Equipment")]
        public XPCollection<device_EquipmentCharacterParam> device_EquipmentCharacterParams { get { return GetCollection<device_EquipmentCharacterParam>("device_EquipmentCharacterParams"); } }
        [Association(@"device_EquipmentErrorReferencesdevice_Equipment")]
        public XPCollection<device_EquipmentError> device_EquipmentErrors { get { return GetCollection<device_EquipmentError>("device_EquipmentErrors"); } }
    }

}
