//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SensorSet.Model.SensorSet
{

    [Persistent(@"device.EquipmentError")]
    public partial class device_EquipmentError : XPLiteObject
    {
        Guid fGUID;
        [Key(true)]
        public Guid GUID
        {
            get { return fGUID; }
            set { SetPropertyValue<Guid>("GUID", ref fGUID, value); }
        }
        device_Measurand fMeasurandGUID;
        [Association(@"device_EquipmentErrorReferencesdevice_Measurand")]
        public device_Measurand MeasurandGUID
        {
            get { return fMeasurandGUID; }
            set { SetPropertyValue<device_Measurand>("MeasurandGUID", ref fMeasurandGUID, value); }
        }
        long fEquipmentID;
        public long EquipmentID
        {
            get { return fEquipmentID; }
            set { SetPropertyValue<long>("EquipmentID", ref fEquipmentID, value); }
        }
        device_Equipment fEquipmentGUID;
        [Association(@"device_EquipmentErrorReferencesdevice_Equipment")]
        public device_Equipment EquipmentGUID
        {
            get { return fEquipmentGUID; }
            set { SetPropertyValue<device_Equipment>("EquipmentGUID", ref fEquipmentGUID, value); }
        }
        decimal fDiapasonBegin;
        public decimal DiapasonBegin
        {
            get { return fDiapasonBegin; }
            set { SetPropertyValue<decimal>("DiapasonBegin", ref fDiapasonBegin, value); }
        }
        decimal fDiapasonEnd;
        public decimal DiapasonEnd
        {
            get { return fDiapasonEnd; }
            set { SetPropertyValue<decimal>("DiapasonEnd", ref fDiapasonEnd, value); }
        }
        short fDeltaType;
        public short DeltaType
        {
            get { return fDeltaType; }
            set { SetPropertyValue<short>("DeltaType", ref fDeltaType, value); }
        }
        decimal fDeltaValue;
        public decimal DeltaValue
        {
            get { return fDeltaValue; }
            set { SetPropertyValue<decimal>("DeltaValue", ref fDeltaValue, value); }
        }
        DateTime fDateOfChange;
        public DateTime DateOfChange
        {
            get { return fDateOfChange; }
            set { SetPropertyValue<DateTime>("DateOfChange", ref fDateOfChange, value); }
        }
        DateTime fDeletedDate;
        public DateTime DeletedDate
        {
            get { return fDeletedDate; }
            set { SetPropertyValue<DateTime>("DeletedDate", ref fDeletedDate, value); }
        }
    }

}
