//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SensorSet.Model.SensorSet
{

    [Persistent(@"device.Measurand")]
    public partial class device_Measurand : XPLiteObject
    {
        Guid fGUID;
        [Key(true)]
        public Guid GUID
        {
            get { return fGUID; }
            set { SetPropertyValue<Guid>("GUID", ref fGUID, value); }
        }
        long fDimensionID;
        public long DimensionID
        {
            get { return fDimensionID; }
            set { SetPropertyValue<long>("DimensionID", ref fDimensionID, value); }
        }
        string fValueName;
        [Size(64)]
        public string ValueName
        {
            get { return fValueName; }
            set { SetPropertyValue<string>("ValueName", ref fValueName, value); }
        }
        list_Dimension fDimensionGUID;
        [Association(@"device_MeasurandReferenceslist_Dimension")]
        public list_Dimension DimensionGUID
        {
            get { return fDimensionGUID; }
            set { SetPropertyValue<list_Dimension>("DimensionGUID", ref fDimensionGUID, value); }
        }
        [Association(@"device_EquipmentErrorReferencesdevice_Measurand")]
        public XPCollection<device_EquipmentError> device_EquipmentErrors { get { return GetCollection<device_EquipmentError>("device_EquipmentErrors"); } }
        [Association(@"device_EquipmentTypeErrorReferencesdevice_Measurand")]
        public XPCollection<device_EquipmentTypeError> device_EquipmentTypeErrors { get { return GetCollection<device_EquipmentTypeError>("device_EquipmentTypeErrors"); } }
    }

}
