//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SensorSet.Model.SensorSet
{

    [Persistent(@"device.EquipmentType")]
    public partial class device_EquipmentType : XPLiteObject
    {
        Guid fGUID;
        [Key(true)]
        public Guid GUID
        {
            get { return fGUID; }
            set { SetPropertyValue<Guid>("GUID", ref fGUID, value); }
        }
        device_EquipmentKind fEquipmentKindGUID;
        [Association(@"device_EquipmentTypeReferencesdevice_EquipmentKind")]
        public device_EquipmentKind EquipmentKindGUID
        {
            get { return fEquipmentKindGUID; }
            set { SetPropertyValue<device_EquipmentKind>("EquipmentKindGUID", ref fEquipmentKindGUID, value); }
        }
        list_Vendor fEquipmentVendorGUID;
        [Association(@"device_EquipmentTypeReferenceslist_Vendor")]
        public list_Vendor EquipmentVendorGUID
        {
            get { return fEquipmentVendorGUID; }
            set { SetPropertyValue<list_Vendor>("EquipmentVendorGUID", ref fEquipmentVendorGUID, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fFullName;
        [Size(SizeAttribute.Unlimited)]
        public string FullName
        {
            get { return fFullName; }
            set { SetPropertyValue<string>("FullName", ref fFullName, value); }
        }
        DateTime fDeletedDate;
        public DateTime DeletedDate
        {
            get { return fDeletedDate; }
            set { SetPropertyValue<DateTime>("DeletedDate", ref fDeletedDate, value); }
        }
        DateTime fDateCreate;
        public DateTime DateCreate
        {
            get { return fDateCreate; }
            set { SetPropertyValue<DateTime>("DateCreate", ref fDateCreate, value); }
        }
        DateTime fDateModify;
        public DateTime DateModify
        {
            get { return fDateModify; }
            set { SetPropertyValue<DateTime>("DateModify", ref fDateModify, value); }
        }
        DateTime fDateOfChange;
        public DateTime DateOfChange
        {
            get { return fDateOfChange; }
            set { SetPropertyValue<DateTime>("DateOfChange", ref fDateOfChange, value); }
        }
       
        auth_Users fChangedUserID;
        [Association(@"device_EquipmentTypeReferencesauth_Users")]
        public auth_Users ChangedUserID
        {
            get { return fChangedUserID; }
            set { SetPropertyValue<auth_Users>("ChangedUserID", ref fChangedUserID, value); }
        }
        [Association(@"device_EquipmentReferencesdevice_EquipmentType")]
        public XPCollection<device_Equipment> device_Equipments { get { return GetCollection<device_Equipment>("device_Equipments"); } }
        [Association(@"device_EquipmentCharacterEquipmentTypeReferencesdevice_EquipmentType")]
        public XPCollection<device_EquipmentCharacterEquipmentType> device_EquipmentCharacterEquipmentTypes { get { return GetCollection<device_EquipmentCharacterEquipmentType>("device_EquipmentCharacterEquipmentTypes"); } }
        [Association(@"device_EquipmentTypeErrorReferencesdevice_EquipmentType")]
        public XPCollection<device_EquipmentTypeError> device_EquipmentTypeErrors { get { return GetCollection<device_EquipmentTypeError>("device_EquipmentTypeErrors"); } }
    }

}
