//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SensorSet.Model.SensorSet
{

    [Persistent(@"device.EquipmentCharacter")]
    public partial class device_EquipmentCharacter : XPLiteObject
    {
        Guid fGUID;
        [Key(true)]
        public Guid GUID
        {
            get { return fGUID; }
            set { SetPropertyValue<Guid>("GUID", ref fGUID, value); }
        }
        string fCharacterName;
        [Size(128)]
        public string CharacterName
        {
            get { return fCharacterName; }
            set { SetPropertyValue<string>("CharacterName", ref fCharacterName, value); }
        }
        string fFieldName;
        [Size(31)]
        public string FieldName
        {
            get { return fFieldName; }
            set { SetPropertyValue<string>("FieldName", ref fFieldName, value); }
        }
        short fParamType;
        public short ParamType
        {
            get { return fParamType; }
            set { SetPropertyValue<short>("ParamType", ref fParamType, value); }
        }
        list_Dimension fDimensionGUID;
        [Association(@"device_EquipmentCharacterReferenceslist_Dimension")]
        public list_Dimension DimensionGUID
        {
            get { return fDimensionGUID; }
            set { SetPropertyValue<list_Dimension>("DimensionGUID", ref fDimensionGUID, value); }
        }
        bool fIsSystem;
        public bool IsSystem
        {
            get { return fIsSystem; }
            set { SetPropertyValue<bool>("IsSystem", ref fIsSystem, value); }
        }
        DateTime fDeletedDate;
        public DateTime DeletedDate
        {
            get { return fDeletedDate; }
            set { SetPropertyValue<DateTime>("DeletedDate", ref fDeletedDate, value); }
        }
        DateTime fDateOfChange;
        public DateTime DateOfChange
        {
            get { return fDateOfChange; }
            set { SetPropertyValue<DateTime>("DateOfChange", ref fDateOfChange, value); }
        }
        [Association(@"device_EquipmentCharacterEquipmentTypeReferencesdevice_EquipmentCharacter")]
        public XPCollection<device_EquipmentCharacterEquipmentType> device_EquipmentCharacterEquipmentTypes { get { return GetCollection<device_EquipmentCharacterEquipmentType>("device_EquipmentCharacterEquipmentTypes"); } }
        [Association(@"device_EquipmentCharacterParamReferencesdevice_EquipmentCharacter")]
        public XPCollection<device_EquipmentCharacterParam> device_EquipmentCharacterParams { get { return GetCollection<device_EquipmentCharacterParam>("device_EquipmentCharacterParams"); } }
        [Association(@"measure_MeteringReferencesdevice_EquipmentCharacter")]
        public XPCollection<measure_Metering> measure_Meterings { get { return GetCollection<measure_Metering>("measure_Meterings"); } }
    }

}
