//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SensorSet.Model.SensorSet
{

    [Persistent(@"list.Vendor")]
    public partial class list_Vendor : XPLiteObject
    {
        Guid fGUID;
        [Key(true)]
        public Guid GUID
        {
            get { return fGUID; }
            set { SetPropertyValue<Guid>("GUID", ref fGUID, value); }
        }
        string fName;
        [Size(128)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fCountryName;
        [Size(64)]
        public string CountryName
        {
            get { return fCountryName; }
            set { SetPropertyValue<string>("CountryName", ref fCountryName, value); }
        }
        [Association(@"device_EquipmentTypeReferenceslist_Vendor")]
        public XPCollection<device_EquipmentType> device_EquipmentTypes { get { return GetCollection<device_EquipmentType>("device_EquipmentTypes"); } }
    }

}
