//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SensorSet.Model.SensorSet
{

    [Persistent(@"measure.Metering")]
    public partial class measure_Metering : XPLiteObject
    {
        DateTime fDateCreated;
        [Key]
        public DateTime DateCreated
        {
            get { return fDateCreated; }
            set { SetPropertyValue<DateTime>("DateCreated", ref fDateCreated, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>("Date", ref fDate, value); }
        }
        device_Equipment fEquipmentGUID;
        [Association(@"measure_MeteringReferencesdevice_Equipment")]
        public device_Equipment EquipmentGUID
        {
            get { return fEquipmentGUID; }
            set { SetPropertyValue<device_Equipment>("EquipmentGUID", ref fEquipmentGUID, value); }
        }
        long fIntParam;
        public long IntParam
        {
            get { return fIntParam; }
            set { SetPropertyValue<long>("IntParam", ref fIntParam, value); }
        }
        string fStrParam;
        [Size(SizeAttribute.Unlimited)]
        public string StrParam
        {
            get { return fStrParam; }
            set { SetPropertyValue<string>("StrParam", ref fStrParam, value); }
        }
        DateTime fDateParam;
        public DateTime DateParam
        {
            get { return fDateParam; }
            set { SetPropertyValue<DateTime>("DateParam", ref fDateParam, value); }
        }
        bool fBoolParam;
        public bool BoolParam
        {
            get { return fBoolParam; }
            set { SetPropertyValue<bool>("BoolParam", ref fBoolParam, value); }
        }
        long fNumericParam;
        public long NumericParam
        {
            get { return fNumericParam; }
            set { SetPropertyValue<long>("NumericParam", ref fNumericParam, value); }
        }
        double fNumericParam2;
        public double NumericParam2
        {
            get { return fNumericParam2; }
            set { SetPropertyValue<double>("NumericParam2", ref fNumericParam2, value); }
        }
        device_EquipmentCharacter fEquipmentCharacterGUID;
        [Association(@"measure_MeteringReferencesdevice_EquipmentCharacter")]
        public device_EquipmentCharacter EquipmentCharacterGUID
        {
            get { return fEquipmentCharacterGUID; }
            set { SetPropertyValue<device_EquipmentCharacter>("EquipmentCharacterGUID", ref fEquipmentCharacterGUID, value); }
        }
    }

}
